### ISSUE TITLE
SharePoint ID获取报错，尝试多次无法解决

### ISSUE THREAD

**Issue by HuYihe2008** [alist-org/docs#142]
在 tool.nn迁移至alist.nn后就不可以使用了
其显示报错类似：Invalid hostname for this tenancy
我输入的是：https://huyihe.sharepoint.com/sites/yunjin
无论使用官方的cilent_id还是我自己的都不可用，不知道是我的问题还是alist官方后台的问题

**Comment by Xhofe** [comment]
fixed in https://github.com/alist-org/docs/commit/f8100e23828d9bea36aabad77a3477dcfc134c8d
