### ISSUE TITLE
网页端不支持上传吗

### ISSUE THREAD

**Issue by wenfer** [alist-org/docs#182]
找遍了也没有找到上传的功能

**Comment by evlic** [comment]
需要在有权限上传的目录下点击上传按钮
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/61658981/226256226-2122bf32-cd07-4a6a-97fb-3f5fdb7bf8d3.png">

**Comment by wenfer** [comment]
> 需要在有权限上传的目录下点击上传按钮 <img alt="image" width="1005" src="https://user-images.githubusercontent.com/61658981/226256226-2122bf32-cd07-4a6a-97fb-3f5fdb7bf8d3.png">

如何让目录有上传权限，元信息已经配了写入，还是没有

**Comment by wenfer** [comment]
找到了，这个按钮实在是太隐蔽了，建议还是放显眼一些吧
