### ISSUE TITLE
希望可以在网盘编辑里自定义UA

### ISSUE THREAD

**Issue by saltfish233** [alist-org/docs#216]
如果能在请求网盘资源时，都使用自己自定义的UA会不会更方便些，比如百度网盘，而不是每次都需要手动修改当前页面的UA

**Comment by anwen-anyi** [comment]
我记得插件改UA头可以设置路径吧~就是例如你进入了百度网盘的他会自动改 你自己配置一下

**Comment by saltfish233** [comment]
> 我记得插件改UA头可以设置路径吧~就是例如你进入了百度网盘的他会自动改 你自己配置一下

我的意思是希望alist实现不同的人登录后请求某网盘的时候都会用我设定好的ua去访问，这样在对于用户来说不需要自己去做配置

**Comment by anwen-anyi** [comment]
> > 我记得插件改UA头可以设置路径吧~就是例如你进入了百度网盘的他会自动改 你自己配置一下
> 
> 我的意思是希望alist实现不同的人登录后请求某网盘的时候都会用我设定好的ua去访问，这样在对于用户来说不需要自己去做配置

我知道说的是什么意思，大概应该不会这样做 所以我说了和问题不相关的另外一种办法，不过欢迎PR~ :smile: :smile: :smile:

**Comment by Xhofe** [comment]
ua是在客户端设置的，如果你开启代理，alist会自动帮你设置对应的ua。如果你使用302跳转，由于是直接从浏览器请求文件的，这属于浏览器级别的设置，alist没有权限修改到浏览器的配置。
